language: python
sudo: false
python:
  - 3.3
  - 3.4

install:
  - pip install -e git+git://github.com/djedproject/djed.renderer#egg=djed.renderer
  - pip install -e git+git://github.com/djedproject/djed.message#egg=djed.message
  - pip install -e .[testing]

script:
  - python setup.py test

notifications:
  email: false
